//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RecorderUI.java
//  @ Date : 07/02/2022
//  @ Author : 
//
//




public class RecorderUI {
}
